export const CUST_LOGIN_REQUEST = "CUST_LOGIN_REQUEST"
export const CUST_LOGIN_SUCCESS = "CUST_LOGIN_SUCCESS"
export const CUST_LOGIN_FAIL = "CUST_LOGIN_FAIL"
export const CUST_LOGOUT_SUCCESS = "CUST_LOGOUT_SUCCESS"

export const CUST_REGISTER_REQUEST = "CUST_REGISTER_REQUEST"
export const CUST_REGISTER_SUCCESS = "CUST_REGISTER_SUCCESS"
export const CUST_REGISTER_FAIL = "CUST_REGISTER_FAIL"