export const SELLER_ORDERS_LIST_REQUEST = "SELLER_ORDERS_LIST_REQUEST"
export const SELLER_ORDERS_LIST_SUCCESS = "SELLER_ORDERS_LIST_SUCCESS"
export const SELLER_ORDERS_LIST_FAIL = "SELLER_ORDERS_LIST_FAIL"

export const AMOUNT_PAID_REQUEST ="AMOUNT_PAID_REQUEST"
export const AMOUNT_PAID_SUCCESS ="AMOUNT_PAID_SUCCESS"
export const AMOUNT_PAID_FAIL ="AMOUNT_PAID_FAIL"

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST"
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS"
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL"