export const SELLER_ORDERS_LIST_REQUEST = "SELLER_ORDERS_LIST_REQUEST"
export const SELLER_ORDERS_LIST_SUCCESS = "SELLER_ORDERS_LIST_SUCCESS"
export const SELLER_ORDERS_LIST_FAIL = "SELLER_ORDERS_LIST_FAIL"