export const GET_SELLER_PRODUCTS_REQUEST = "GET_SELLER_PRODUCTS_REQUEST"
export const GET_SELLER_PRODUCTS_SUCCESS = "GET_SELLER_PRODUCTS_SUCCESS"
export const GET_SELLER_PRODUCTS_FAIL = "GET_SELLER_PRODUCTS_FAIL"

