export const GET_SELLER_PRODUCTS_REQUEST = "GET_SELLER_PRODUCTS_REQUEST"
export const GET_SELLER_PRODUCTS_SUCCESS = "GET_SELLER_PRODUCTS_SUCCESS"
export const GET_SELLER_PRODUCTS_FAIL = "GET_SELLER_PRODUCTS_FAIL"

export const GET_SELLER_PRODUCT_DETAILS_REQUEST = "GET_SELLER_PRODUCT_DETAILS_REQUEST"
export const GET_SELLER_PRODUCT_DETAILS_SUCCESS = "GET_SELLER_PRODUCT_DETAILS_SUCCESS"
export const GET_SELLER_PRODUCT_DETAILS_FAIL = "GET_SELLER_PRODUCT_DETAILS_FAIL"

