export const SELLER_LOGIN_REQUEST = "SELLER_LOGIN_REQUEST"
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS"
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL"
export const SELLER_LOGOUT_SUCCESS = "SELLER_LOGOUT_SUCCESS"

export const SELLER_REGISTER_REQUEST = "SELLER_REGISTER_REQUEST"
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS"
export const SELLER_REGISTER_FAIL = "SELLER_REGISTER_FAIL"

export const SELLER_DETAILS_REQUEST = "SELLER_DETAILS_REQUEST"
export const SELLER_DETAILS_SUCCESS = "SELLER_DETAILS_SUCCESS"
export const SELLER_DETAILS_FAIL = "SELLER_DETAILS_FAIL"

export const SELLER_GET_CUSTOMERS_LIST_REQUEST = "SELLER_GET_CUSTOMERS_LIST_REQUEST"
export const SELLER_GET_CUSTOMERS_LIST_SUCCESS = "SELLER_GET_CUSTOMERS_LIST_SUCCESS"
export const SELLER_GET_CUSTOMERS_LIST_FAIL = "SELLER_GET_CUSTOMERS_LIST_FAIL"