export const SELLER_LOGIN_REQUEST = "SELLER_LOGIN_REQUEST"
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS"
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL"

export const SELLER_REGISTER_REQUEST = "SELLER_REGISTER_REQUEST"
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS"
export const SELLER_REGISTER_FAIL = "SELLER_REGISTER_FAIL"


